#!/usr/bin/env bash
#script loops from 1 to 10 with iterations


phrase1="bad luck"
phrase2="good luck"
phrase="Best School"
counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "$phrase1"
	elif [ $counter -eq 8 ]
	then
		echo "$phrase2"
	else
		echo "$phrase"
	fi
	((counter++))
done
