#!/usr/bin/env bash
#printing numbers using case


exp1="bad luck from China"
exp2="bad luck from Japan"
exp3="bad luck from Italy"

counter=1

while [ $counter -le 20 ]
do
	case $counter in

		5) echo "$exp1"
		echo "5"
			;;

		10) echo "$exp2"
		echo "10"
		
			;;
		18)
			echo "$exp3"
			echo "18"
			;;

		*)
			echo "$counter"
			;;

	esac
	((counter++))
done
