#!/usr/bin/env bash
#script that gives information

if [ -e school ]
then
	if [ -s school ]
	then
	echo "school file is not empty"
else
	echo "school file is empty"
fi

if [ -f school ]

then
	echo "school is a regular file"
else
	:
fi
else
	echo "school file does not exist"
fi
